name: CI

# CRDT-SQLite CI configuration:
# - Test on Linux (GCC 12, Clang 18), macOS, Windows
# - Both Debug and Release builds
# - Combined ASan + UBSan for memory safety
# - Validates SQLite CRDT wrapper implementation
#
# Note: Thread sanitizer not used (CRDTSQLite is not thread-safe by design)
#
# For local testing: mkdir build && cd build && cmake .. && cmake --build . && ctest

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc-12, cxx: g++-12 }
          - { cc: clang-18, cxx: clang++-18 }
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          libsqlite3-dev \
          ${{ matrix.compiler.cc }} \
          ${{ matrix.compiler.cxx }}

    - name: Configure CMake
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --verbose

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-linux-${{ matrix.compiler.cc }}-${{ matrix.build_type }}
        path: |
          build/Testing/
          build/**/*.log

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake ninja sqlite3

    - name: Configure CMake
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --verbose

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-macos-${{ matrix.build_type }}
        path: |
          build/Testing/
          build/**/*.log

  test-swift-macos:
    name: Test Swift on macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode: ['16.1', '16.4']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

    - name: Print Swift version
      run: swift --version

    - name: Build Swift package
      run: swift build -v

    - name: Run Swift tests
      run: swift test --parallel

    - name: Build for iOS Simulator
      run: |
        xcodebuild -scheme CRDTSQLite \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -derivedDataPath .build \
          build

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-swift-macos-xcode-${{ matrix.xcode }}
        path: |
          .build/
          **/*.log

  test-swift-linux:
    name: Test Swift on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift-version: ['5.9', '5.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}

    - name: Install SQLite
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev

    - name: Print Swift version
      run: swift --version

    - name: Build Swift package
      run: swift build -v

    - name: Run Swift tests
      run: swift test --parallel

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-swift-linux-${{ matrix.swift-version }}
        path: |
          .build/
          **/*.log

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build SQLite from source
      shell: pwsh
      run: |
        # Download SQLite amalgamation
        $SQLITE_VERSION = "3470200"
        $SQLITE_YEAR = "2024"
        Invoke-WebRequest -Uri "https://www.sqlite.org/$SQLITE_YEAR/sqlite-amalgamation-$SQLITE_VERSION.zip" -OutFile sqlite.zip
        Expand-Archive sqlite.zip -DestinationPath .

        # Compile SQLite with FULLMUTEX threading (SQLITE_THREADSAFE=1)
        cd sqlite-amalgamation-$SQLITE_VERSION
        cl /c /O2 /DSQLITE_THREADSAFE=1 /DSQLITE_ENABLE_COLUMN_METADATA sqlite3.c
        lib /OUT:sqlite3.lib sqlite3.obj

        # Create include directory
        New-Item -ItemType Directory -Force -Path ../sqlite_install/include
        New-Item -ItemType Directory -Force -Path ../sqlite_install/lib
        Copy-Item sqlite3.h ../sqlite_install/include/
        Copy-Item sqlite3.lib ../sqlite_install/lib/
        cd ..

    - name: Configure CMake
      run: |
        cmake -B build `
          -G "Visual Studio 17 2022" `
          -A x64 `
          -DCMAKE_PREFIX_PATH="$PWD/sqlite_install" `
          -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run tests with debugger on failure
      shell: pwsh
      run: |
        cd build

        # First try normal test run
        $testFailed = $false
        try {
          ctest -C ${{ matrix.build_type }} --output-on-failure --verbose
        } catch {
          $testFailed = $true
        }

        # If test failed, run with WinDbg-like output for better stack traces
        if ($testFailed -or $LASTEXITCODE -ne 0) {
          Write-Host "`n=== TEST FAILED - Running with detailed crash info ===`n"

          # Find the test executable
          $testExe = Get-ChildItem -Path . -Recurse -Filter "test_crdt_sqlite.exe" | Select-Object -First 1

          if ($testExe) {
            Write-Host "Found test executable: $($testExe.FullName)"
            Write-Host "`n=== Running test directly to capture crash ===`n"

            # Run directly and capture any crash
            & $testExe.FullName 2>&1 | Tee-Object -FilePath "test_crash_output.log"

            Write-Host "`n=== Test executable exit code: $LASTEXITCODE ===`n"
          }

          exit 1
        }

    - name: Upload test results and crash logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-windows-${{ matrix.build_type }}
        path: |
          build/Testing/
          build/**/*.log
          build/test_crash_output.log

  sanitizers:
    name: Sanitizers (ASan + UBSan)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          libsqlite3-dev \
          clang-18

    - name: Configure CMake with sanitizers
      env:
        CC: clang-18
        CXX: clang++-18
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TESTS=ON \
          -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer" \
          -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"

    - name: Build
      run: cmake --build build

    - name: Run tests with sanitizers
      run: |
        cd build
        ctest --output-on-failure --verbose

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: false  # Disabled for now - TODO: fix coverage build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          libsqlite3-dev \
          gcovr \
          gcc-12 \
          g++-12

    - name: Configure CMake with coverage
      env:
        CC: gcc-12
        CXX: g++-12
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TESTS=ON \
          -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage"

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Generate coverage report
      run: |
        gcovr --root . --filter 'crdt.*\.(hpp|cpp)' \
          --exclude '.*test.*' \
          --print-summary \
          --xml coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
